### ISSUE TITLE
使用宏重构后的版本，选中的内容不正确

### ISSUE THREAD

**Issue by ringawho** [manateelazycat/markmacro#6]
今天pull了最新的代码，发现执行 `markmacro-mark-words` 以及 `markmacro-mark-lines` 后选中的内容不正确，看了一下 `markmacro-mark-objects` 这个宏，由于中间执行了一次 `deactivate-mark`，导致第二次执行的时候获取的区域是错误的，应该还是需要一个 `let` 去暂存一下 `mark-bound` 执行结果

``` emacs-lisp
;; 以markmacro-mark-lines为例，mark-bound内容为：
(if (region-active-p)
    (cons (region-beginning) (region-end))   ; 第一次会用选中区域
  (cons (point-min) (point-max))             ; 第二次会用这个，会直接选中整个buffer

(cl-defmacro markmacro-mark-objects (mark-bound func)
  `(when ,mark-bound
     (when (region-active-p)
       (deactivate-mark))                    ; 这里关闭了 region

     (dolist (bound (funcall ,func ,mark-bound))
       (let* ((overlay (make-overlay (car bound) (cdr bound))))
         (overlay-put overlay 'face 'markmacro-mark-face)
         (add-to-list 'markmacro-overlays overlay t)))

     (markmacro-select-last-overlay)))
```

**Comment by manateelazycat** [comment]
给一个详细的重现例子和步骤吧，谢谢

**Comment by ringawho** [comment]
https://user-images.githubusercontent.com/18455821/214197146-8c7d386f-b1f4-49e8-9796-fd6fb57e6101.mp4

1. git clone https://github.com/manateelazycat/markmacro.git
2. 通过emacs -Q启动
3. require mark-macro
4. 选中最后两行
5. 执行markmacro-mark-lines

预期的情况应该是只有最后两行高亮，但是实际是整个buffer都高亮了

**Comment by manateelazycat** [comment]
更新吧， 已经修复了。
